spring:
  # DB (접속정보 -> 환경변수)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA 설정
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: create

  # Redis 설정 (비밀번호 -> 환경변수)
  redis:
    host: ec2-52-79-82-151.ap-northeast-2.compute.amazonaws.com
    port: 6379

  # Oauth Login
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 208682346817-5t05smljuv1odp30ctgd97n6b4sjucun.apps.googleusercontent.com
            # client-secret -> 환경변수
            scope:
              - email
              - profile
          kakao:
            client-id: b14fc5d2c866ed1b260695c1b46dfab5
            # client-secret -> 환경변수
            scope:
              - account_email
              - profile_nickname
            authorization-grant-type: authorization_code
            redirect-uri: http://ec2-52-79-82-151.ap-northeast-2.compute.amazonaws.com:8085/login/oauth2/code/kakao
            #redirect-uri: http://localhost:8085/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: POST

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

# 포트 설정 및 한글 깨짐 현상 방지
server:
  port: 8085
  servlet:
    encoding:
      force-response: true

# Jwt Token 유지 시간
jwt:
  duration:
    access-token: 1800   # 30분 = 1800초
    refresh-token: 604800   # 7일 = 168시간 = 10080분 = 604800초

