spring:
  # DB (접속정보 -> 환경변수)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA 설정
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: create

  # Redis 설정 (비밀번호 -> 환경변수)
  redis:
    host: ec2-52-79-82-151.ap-northeast-2.compute.amazonaws.com
    port: 6379

# 포트 설정 및 한글 깨짐 현상 방지
server:
  port: 8085
  servlet:
    encoding:
      force-response: true

# Jwt Token 유지 시간
jwt:
  duration:
    access-token: 60   # 30분 = 1800초
    refresh-token: 180   # 7일 = 168시간 = 10080분 = 604800초
